### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by reify-qa** [cognitect/transit-python#37]
Hi there,
Is it possible to release latest code changes for this library?

**Problem:**
I'm interested in this library and would like to use it with python 3.9.
It's possible to do with latest code base.
However, it's not released, so couldn't be obtained via pip install

**Possible solution:**
Release latest code version

CC: @benkamphaus

**Comment by seltzered** [comment]
seconding the release request, latest stable release (0.8.302) doesn't work on python 3.10 and runs into [the "cannot import name 'Mapping'](https://github.com/cognitect/transit-python/issues/34). 

As a workaround, one can do:
`pip install git+https://github.com/cognitect/transit-python.git`

**Comment by 3wnbr1** [comment]
Hey there
As this package seemed unmaintained, I took the opportunity to fork it as [transit-python2](https://github.com/3wnbr1/transit-python2) available on [PYPI](https://pypi.org/project/transit-python2/) as a drop in replacement. Of course your feedback and pull requests are welcome
